### ISSUE TITLE
Android Flutter - App crashing while joining the room

### ISSUE THREAD

**Issue by Komal-Khairnar** [100mslive/100ms-flutter#300]
java.lang.NoSuchMethodError: No virtual method getCustomerDescription()Ljava/lang/String; in class Llive/hms/video/sdk/models/HMSPeer; or its super classes (declaration of 'live.hms.video.sdk.models.HMSPeer')

	at live.hms.hmssdk_flutter.HMSPeerExtension$Companion.toDictionary(HMSPeerExtension.kt:19)
 	at live.hms.hmssdk_flutter.HMSRoomExtension$Companion.toDictionary(HMSRoomExtension.kt:18)
	at live.hms.hmssdk_flutter.HmssdkFlutterPlugin.onJoin(HmssdkFlutterPlugin.kt:245)
	at live.hms.video.sdk.SDKDelegate$onPeerListNotificationHandled$1.invokeSuspend(SDKDelegate.kt:530)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

**Comment by ygit** [comment]
@Komal-Khairnar in the latest version of Native Android SDK, `customerDescription` property of `HMSPeer` has been renamed to `metadata` 
We'll be releasing updated version of Flutter SDK to make it compatible. Meanwhile, you can use an older version of Native Android SDK i.e.  version `2.2.0`

https://docs.100ms.live/android/v2/release-notes/Release-Notes#2-2-0-2021-11-19

**Comment by ygit** [comment]
@Komal-Khairnar were you able to resolve the issue?
