### ISSUE TITLE
app crashing after join is called

### ISSUE THREAD

**Issue by abbas2501** [100mslive/100ms-flutter#416]
What happens -

1. User joins the meeting (can see that on 100ms dashboard)
2. 2 seconds pause
3. App crashes
4. User leaves the meeting

Code --

```
Future<HMSSDK> join() async {
    meeting.build();

    try {

      final HMSConfig? config = getHmsConfig();

      print("HMS CONFIG -- ${config?.userName}");

      await meeting.join(
        config: config!,
      );
      print("Success join..hms");
      localPeer = await meeting.getLocalPeer();

  // This also triggers
      print("Local peer --- ${localPeer?.videoTrack}");

// This also triggers
      log("Local Peer updated - ${localPeer?.name}",
          name: "HMS local peer updated");

      isRemoved = false;
      meeting.addMeetingListener(listener: this);
      
// This also triggers
log("HMS Joined.... ");
      return meeting;
    } catch (exception) {

// THIS IS NOT TRIGGERED!
      log("hms Failed to join - ${exception.toString()}");
      this.leaveMeeting();
      throw exception;
    }
  }
```

Conclusion -- No matter if I add breakpoints or without breakpoints, join() is called and after that, every piece of code is running fine (print statements are logging) BUT the app still crashes after a second or two.

Please note - no other callback from the ones provided by **HMSUpdateListener** are triggered, not even void onError({required HMSException error})

**Comment by abbas2501** [comment]
LOGS before crash

```
/flutter (28414): HMS CONFIG -- Abbas + A
D/HMSPeerConnectionFactory(28414): Encoder supported Codecs: [VP8, VP9, AV1X, H264]
D/HMSPeerConnectionFactory(28414): Decoder supported Codecs: [VP8, VP9, AV1X, H264, H264]
I/flutter (28414): Success join..hms
D/HMSTransport(28414): connect: started ⏰
D/HMSUtils(28414): getUserAgent: hmsClient/2.2.6 Android/30 (EB2101)
D/InitService(28414): makeInitRequest: request=Request{method=GET, url=https://prod-init.100ms.live/init?user_agent=hmsClient%2F2.2.6+Android%2F30+%28EB2101%29, headers=[Authorization:Bearer (token hide).eyJhY2Nlc3Nfa2V5IjoiNjE3YTY5OGNhZjMxODhkZjMzZTY0MWQyIiwicm9vbV9pZCI6IjYxODEwMzdjYWYzMTg4ZGYzM2U2NWViNyIsInVzZXJfaWQiOiI2MTdhNjk4Y2FmMzE4OGRmMzNlNjQxY2UiLCJyb2xlIjoic3R1ZGVudCIsImp0aSI6ImVkYzljM2JiLTE4OTktNDg1Ni04YzliLWNiYjc2ZmE5M2U4YSIsInR5cGUiOiJhcHAiLCJ2ZXJzaW9uIjoyLCJleHAiOjE2NDI4Mzk5NzJ9.7gCjZ4dWf7ftx4d-yQo2_04dhcJ6_aw3ewRbYaxBo6E, Accept-Type:application/json]}
[HMS local peer updated] Local Peer updated - Abbas + A
[log] HMS Joined....
D/InitService(28414): fetchInitConfig: response=Response{protocol=h2, code=200, message=, url=https://prod-init.100ms.live/init?user_agent=hmsClient%2F2.2.6+Android%2F30+%28EB2101%29}
D/HMSUtils(28414): getUserAgent: hmsClient/2.2.6 Android/30 (EB2101)
D/JsonRPCSignal(28414): open: Connecting WebSocket to endpoint=wss://prod-in2.100ms.live/v2/ws?peer=2b33048e-cef3-4af2-8de6-2d469dcc6d41&token=(token hide).eyJhY2Nlc3Nfa2V5IjoiNjE3YTY5OGNhZjMxODhkZjMzZTY0MWQyIiwicm9vbV9pZCI6IjYxODEwMzdjYWYzMTg4ZGYzM2U2NWViNyIsInVzZXJfaWQiOiI2MTdhNjk4Y2FmMzE4OGRmMzNlNjQxY2UiLCJyb2xlIjoic3R1ZGVudCIsImp0aSI6ImVkYzljM2JiLTE4OTktNDg1Ni04YzliLWNiYjc2ZmE5M2U4YSIsInR5cGUiOiJhcHAiLCJ2ZXJzaW9uIjoyLCJleHAiOjE2NDI4Mzk5NzJ9.7gCjZ4dWf7ftx4d-yQo2_04dhcJ6_aw3ewRbYaxBo6E&user_agent=hmsClient/2.2.6 Android/30 (EB2101) ⏰
D/HMSWebSocketListener(28414): onOpen response=Response{protocol=http/1.1, code=101, message=Switching Protocols, url=https://prod-in2.100ms.live/v2/ws?peer=2b33048e-cef3-4af2-8de6-2d469dcc6d41&token=(token hide).eyJhY2Nlc3Nfa2V5IjoiNjE3YTY5OGNhZjMxODhkZjMzZTY0MWQyIiwicm9vbV9pZCI6IjYxODEwMzdjYWYzMTg4ZGYzM2U2NWViNyIsInVzZXJfaWQiOiI2MTdhNjk4Y2FmMzE4OGRmMzNlNjQxY2UiLCJyb2xlIjoic3R1ZGVudCIsImp0aSI6ImVkYzljM2JiLTE4OTktNDg1Ni04YzliLWNiYjc2ZmE5M2U4YSIsInR5cGUiOiJhcHAiLCJ2ZXJzaW9uIjoyLCJleHAiOjE2NDI4Mzk5NzJ9.7gCjZ4dWf7ftx4d-yQo2_04dhcJ6_aw3ewRbYaxBo6E&user_agent=hmsClient/2.2.6%20Android/30%20(EB2101)}
D/JsonRPCSignal(28414): open: WebSocket connected to endpoint=wss://prod-in2.100ms.live/v2/ws?peer=2b33048e-cef3-4af2-8de6-2d469dcc6d41&token=(token hide).eyJhY2Nlc3Nfa2V5IjoiNjE3YTY5OGNhZjMxODhkZjMzZTY0MWQyIiwicm9vbV9pZCI6IjYxODEwMzdjYWYzMTg4ZGYzM2U2NWViNyIsInVzZXJfaWQiOiI2MTdhNjk4Y2FmMzE4OGRmMzNlNjQxY2UiLCJyb2xlIjoic3R1ZGVudCIsImp0aSI6ImVkYzljM2JiLTE4OTktNDg1Ni04YzliLWNiYjc2ZmE5M2U4YSIsInR5cGUiOiJhcHAiLCJ2ZXJzaW9uIjoyLCJleHAiOjE2NDI4Mzk5NzJ9.7gCjZ4dWf7ftx4d-yQo2_04dhcJ6_aw3ewRbYaxBo6E&user_agent=hmsClient/2.2.6 Android/30 (EB2101) ✅
D/HMSTransport(28414): connect: successful ✅
D/HMSTransport(28414): Transport state change: Disconnected -> Connected
D/HMSTransport(28414): join: started ⏰
D/HMSConfiguration(28414): parsed ice-server: [[turn:turn-in.100ms.live, turn:turn-in.100ms.live?transport=tcp, turn:turn-in.100ms.live:443, turn:turn-in.100ms.live:443?transport=tcp] [1642843089::ioi30n942v4TPh35+tg2AQ+b2Wk=] [TLS_CERT_POLICY_SECURE] [] [null] [null]]
I/HMSTransport(28414): Joining with name=Abbas + A & config=live.hms.video.connection.models.HMSConfiguration@a744246
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onRenegotiationNeeded
I/HMSPublishConnection(28414): Created data-channel `ion-sfu`
I/HMSDataChannel(28414): Created data channel HMSDataChannel{id=-1, label=ion-sfu, metadata=[role=PUBLISH]}
D/HMSTransport(28414): join: Starting offer negotiation with server
D/HMSPublishConnection(28414): Ignoring onRenegotiationNeeded as data-channel with label=ion-sfu will be negotiate during join
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onSignalingChange: newState=HAVE_LOCAL_OFFER
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceGatheringChange: newState=GATHERING
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:3322842389 1 udp 2122000639 2409:4053:2d8e:9cab:b3d2:5ec1:d99a:6eeb 40318 typ host generation 0 ufrag 4izH network-id 5 network-cost 900::UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:3807197000 1 udp 2121932543 26.23.71.228 38833 typ host generation 0 ufrag 4izH network-id 6 network-cost 900::UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:559267639 1 udp 2121874687 ::1 40478 typ host generation 0 ufrag 4izH network-id 2::UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:1510613869 1 udp 2121801471 127.0.0.1 45255 typ host generation 0 ufrag 4izH network-id 1::UNKNOWN
D/SDKDelegate(28414): method=on-policy-change params=PolicyChange(roleName=student, rolesMap={teacher=HMSRole(name=teacher, publishParams=PublishParams(audio=AudioParams(bitRate=32, codec=OPUS), video=VideoParams(bitRate=700, codec=VP8, frameRate=30, width=960, height=720), screen=VideoParams(bitRate=0, codec=VP8, frameRate=10, width=1920, height=1080), allowed=[audio, video, screen]), subscribeParams=SubscribeParams(subscribeTo=[teacher, student], maxSubsBitRate=8000, subscribeDegradationParam=SubscribeDegradationParams(packetLossThreshold=25, degradeGracePeriodSeconds=1, recoverGracePeriodSeconds=4)), permission=PermissionsParams(endRoom=true, removeOthers=true, unmute=true, mute=true, changeRole=true, changeRoleForce=false, rtmp=false, recording=false), priority=1), student=HMSRole(name=student, publishParams=PublishParams(audio=AudioParams(bitRate=32, codec=OPUS), video=VideoParams(bitRate=300, codec=VP8, frameRate=30, width=480, height=360), screen=VideoParams(bitRate=0, codec=VP8, frameRate=10, width=1920, height=1080), allowed=[audio, video]), subscribeParams=SubscribeParams(subscribeTo=[teacher, student], maxSubsBitRate=3200, subscribeDegradationParam=SubscribeDegradationParams(packetLossThreshold=25, degradeGracePeriodSeconds=1, recoverGracePeriodSeconds=4)), permission=PermissionsParams(endRoom=false, removeOthers=false, unmute=false, mute=false, changeRole=false, changeRoleForce=false, rtmp=false, recording=false), priority=1)})
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:3164758873 1 tcp 1518283007 2409:4053:2d8e:9cab::d6 9 typ host tcptype active generation 0 ufrag 4izH network-id 8 network-cost 10::UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:2490051814 1 tcp 1518214911 192.168.119.234 9 typ host tcptype active generation 0 ufrag 4izH network-id 7 network-cost 10::UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:2981478324 1 tcp 1518151935 2402:8100:6168:e479:371b:b278:d78c:dfba 9 typ host tcptype active generation 0 ufrag 4izH network-id 3 network-cost 900::UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:1325598741 1 tcp 1518086399 2409:4013:2d8c:f676:63c1:e864:b1a8:4e1e 9 typ host tcptype active generation 0 ufrag 4izH network-id 4 network-cost 900::UNKNOWN

D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:842163049 1 udp 1685724927 132.154.108.201 36873 typ srflx raddr 26.23.71.228 rport 38833 generation 0 ufrag 4izH network-id 6 network-cost 900:stun:35.200.180.208:3478:UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:842163049 1 udp 1685724927 132.154.108.201 38833 typ srflx raddr 26.23.71.228 rport 38833 generation 0 ufrag 4izH network-id 6 network-cost 900:stun:35.200.180.208:443:UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:27778368 1 udp 41558015 34.93.20.48 51009 typ relay raddr 132.154.108.201 rport 38833 generation 0 ufrag 4izH network-id 6 network-cost 900:turn:35.200.180.208:443?transport=udp:UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:27778368 1 udp 41558527 34.93.20.48 62728 typ relay raddr 132.154.108.201 rport 36873 generation 0 ufrag 4izH network-id 6 network-cost 900:turn:35.200.180.208:3478?transport=udp:UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:1327767984 1 udp 24781055 34.93.20.48 57252 typ relay raddr 132.154.108.201 rport 49725 generation 0 ufrag 4izH network-id 6 network-cost 900:turn:35.200.180.208:3478?transport=tcp:UNKNOWN
D/HMSPeerConnectionObserver(28414): [role=PUBLISH] onIceCandidate: candidate=0:0:candidate:1327767984 1 udp 24780543 34.93.20.48 51635 typ relay raddr 132.154.108.201 rport 47597 generation 0 ufrag 4izH network-id 6 network-cost 900:turn:35.200.180.208:443?transport=tcp:UNKNOWN
E/AndroidRuntime(28414): 	at live.hms.video.utils.MicrophoneUtils$Companion.isMicrophoneAccessAvailable(MicrophoneUtils.kt:15)
E/AndroidRuntime(28414): 	at live.hms.video.sdk.SDKDelegate.initLocalTracks(SDKDelegate.kt:477)
E/AndroidRuntime(28414): 	at live.hms.video.sdk.SDKDelegate.getLocalTracksByRoleAndApplySettings(SDKDelegate.kt:456)
E/AndroidRuntime(28414): 	at live.hms.video.sdk.SDKDelegate.access$getLocalTracksByRoleAndApplySettings(SDKDelegate.kt:41)
E/AndroidRuntime(28414): 	at live.hms.video.sdk.SDKDelegate$onPolicyChangeHandled$1.invokeSuspend(SDKDelegate.kt:341)

```

**Comment by ygit** [comment]
@abbas2501 HMSSDK object initialization & calling `build()` function on it should be done at the same place. Also attach meeting listeners before calling `join`

```
HMSSDK hmsSDK = HMSSDK();
hmsSDK.build();
hmsSDK.addMeetingListener(updateListener);
...
final HMSConfig? config = getHmsConfig();
await meeting.join(
    config: config!,
);
```

Once you get `onJoin` callback then proceed to get `localPeer` & other operations.
If joining room fails, you'll get `onError` callback of [HMSUpdateListener](https://github.com/100mslive/100ms-flutter/blob/main/lib/src/model/hms_update_listener.dart)

https://github.com/100mslive/100ms-flutter/blob/88fdb4bcd0dfc1f5f33c7b5646817a1411a4bfc5/lib/src/model/hms_update_listener.dart#L19

https://github.com/100mslive/100ms-flutter/blob/88fdb4bcd0dfc1f5f33c7b5646817a1411a4bfc5/lib/src/hmssdk.dart#L520

**Comment by ygit** [comment]
@abbas2501 were you able to resolve the issue?

**Comment by abbas2501** [comment]
Not really! I was doubtful of my implementation so was checking on that. Also this implementation was working perfectly fine with the previous version of the SDK but that had more issues.

Can you confirm for me if this is an actual SDK issue ?

**Comment by ygit** [comment]
Nope, this is not an SDK issue.

**Comment by ygit** [comment]
@abbas2501 Also, ensure that Microphone & Camera permissions are given before invoking the `join` API.

**Comment by abbas2501** [comment]
Hi.. the permissions were the real issue. Previously they were not required and adding them to Manifest was sufficient. Now, we need to explicitly ask for permissions.
