### ISSUE TITLE
FATAL crashing app - android.opengl.GLException: Failed to create EGL context: 0x3000

### ISSUE THREAD

**Issue by abbas2501** [100mslive/100ms-flutter#882]
![image](https://user-images.githubusercontent.com/93256186/196113512-688954de-507f-4764-b411-6a68a6895221.png)

If this helps - https://github.com/flutter-webrtc/flutter-webrtc/issues/793#issuecomment-1073161241

**Comment by abbas2501** [comment]
LOGS

```
org.webrtc.EglBase14Impl in createEglContext at line 9
org.webrtc.EglBase14Impl in <init> at line 7
org.webrtc.o0 in f at line 2
org.webrtc.o0 in c at line 4
org.webrtc.EglRenderer in lambda$init$0 at line 4
org.webrtc.EglRenderer in d
org.webrtc.j in run at line 6
org.webrtc.ThreadUtils$4 in call at line 2
org.webrtc.ThreadUtils$4 in call at line 1
org.webrtc.ThreadUtils$3 in run at line 1
android.os.Handler in handleCallback at line 938
android.os.Handler in dispatchMessage at line 99
org.webrtc.EglRenderer$HandlerWithExceptionCallback in dispatchMessage at line 1
android.os.Looper in loop at line 233
android.os.HandlerThread in run at line 67
org.webrtc.ThreadUtils in invokeAtFrontUninterruptibly at line 11
org.webrtc.ThreadUtils in invokeAtFrontUninterruptibly at line 16
org.webrtc.EglRenderer in init at line 10
org.webrtc.EglRenderer in init at line 20
org.webrtc.SurfaceEglRenderer in init at line 9
org.webrtc.SurfaceViewRenderer in init at line 6
org.webrtc.SurfaceViewRenderer in init at line 1
live.hms.hmssdk_flutter.views.HMSVideoView in onAttachedToWindow at line 2
android.view.View in dispatchAttachedToWindow at line 20626
android.view.ViewGroup in dispatchAttachedToWindow at line 3514
android.view.ViewGroup in dispatchAttachedToWindow at line 3521
4
android.view.ViewRootImpl in performTraversals at line 2726
android.view.ViewRootImpl in doTraversal at line 2206
android.view.ViewRootImpl$TraversalRunnable in run at line 8763
android.view.Choreographer$CallbackRecord in run at line 1352
android.view.Choreographer in doCallbacks at line 1149
android.view.Choreographer in doFrame at line 1049
android.view.Choreographer$FrameHandler in handleMessage at line 1275
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loop at line 233
android.app.ActivityThread in main at line 8068
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 631
com.android.internal.os.ZygoteInit in main at line 978
GLException
Failed to create EGL context: 0x3000
```

**Comment by Decoder07** [comment]
Hi, @abbas2501  Please share more details and steps to repro this.

**Comment by abbas2501** [comment]
> Hi, @abbas2501 Please share more details and steps to repro this.

Please check this -- very closely related -- https://github.com/flutter-webrtc/flutter-webrtc/issues/793#issuecomment-1073161241

**Comment by ashish-jajoria** [comment]
Hi @Decoder07 we're also having this same issue.


```
Fatal Exception: java.lang.RuntimeException: android.opengl.GLException: Failed to create EGL context: 0x3000
       at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:284)
       at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:79)
       at org.webrtc.EglBase.createEgl14(EglBase.java:215)
       at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:2)
       at org.webrtc.EglBase.create(EglBase.java:158)
       at org.webrtc.EglBase$-CC.create(EglBase.java:4)
       at org.webrtc.EglRenderer.lambda$init$0(EglRenderer.java:241)
       at org.webrtc.EglRenderer.$r8$lambda$miQc1-F9Qqw0EkFhtMh5sNQ-7uU(EglRenderer.java)
       at org.webrtc.EglRenderer$$InternalSyntheticLambda$0$6dedfabe262485e4a4d65cf85bd66a86aea7230d17ef16df66a4adbea251866d$0.run(EglRenderer.java:6)
       at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
       at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
       at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
       at android.os.Looper.loop(Looper.java:233)
       at android.os.HandlerThread.run(HandlerThread.java:67)
       at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
       at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
       at org.webrtc.EglRenderer.init(EglRenderer.java:232)
       at org.webrtc.EglRenderer.init(EglRenderer.java:259)
       at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
       at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
       at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
       at live.hms.hmssdk_flutter.views.HMSVideoView.onAttachedToWindow(HMSVideoView.kt:40)
       at android.view.View.dispatchAttachedToWindow(View.java:20626)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3514)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2726)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2206)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8763)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
       at android.view.Choreographer.doFrame(Choreographer.java:1049)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8068)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by Decoder07** [comment]
@ashish-jajoria  can you tell when do you get this ?

**Comment by abbas2501** [comment]
hey guys, any update on this, please? This is crucial cause it crashes the app resulting in a bad user experience.

**Comment by ygit** [comment]
hey @abbas2501 
We have released a new version of "hmssdk_flutter" version [0.7.8](https://github.com/100mslive/100ms-flutter/releases/tag/0.7.8)
Do upgrade & try out this. Let us know how it goes.

Also, we can also get on a call: https://calendly.com/yogesh-singh-100ms/30min

**Comment by ygit** [comment]
hey @abbas2501 
Were you able to resolve this issue?

**Comment by redfearnk** [comment]
I am also having this crash
